name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
env:
  TERRAFORM_WORKING_DIRECTORY: terraform

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
          # Fail if "npm run build" generated new changes in dist
          # git update-index --refresh dist/* && git diff-index --quiet HEAD dist

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13
          terraform_wrapper: false
          
      - name: Terraform Init
        id: init
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terraform init

      - uses: ./
        with:
          args: -var-file=./vars/vars.tfvars
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
          report-title: Single Argument Run

      - uses: ./
        with:
          args: '["-lock=false", "-var-file=./vars/vars.tfvars"]'
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
          report-title: Multiple Argument Run
          
  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git
        branches: |
          [
            "+([0-9])?(.{+([0-9]),x}).x",
            "main",
            "next",
            "next-major",
            {
              "name": "beta",
              "prerelease": true
            },
            {
              "name": "alpha",
              "prerelease": true
            }
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Move major version tag
      if: steps.semantic.outputs.new_release_published == 'true'
      env:
        VERION_TAG: v${{steps.semantic.outputs.new_release_major_version}}
      run: |
        git tag -d v${{ env.VERION_TAG }}
        git push origin :v${{ env.VERION_TAG }}
        git tag v${{ env.VERION_TAG }} ${{ env.GITHUB_SHA }}
        git push origin v${{ env.VERION_TAG }}